### ISSUE TITLE
Failed to Catch Fish

### ISSUE THREAD

**Issue by AinunNajib08** [nafalabi/albn-fishing-bot#1]
Hi bro, 
Thank you for making this app.

I have problem when try it.
First, I always failed to catch fish. 

precisely when holding down the click button. The system always doesn't hold back the click to get the fish.
Maybe I can see the setting of Albion. Graphics, resolution etc

Thank you bro

**Comment by nafalabi** [comment]
@AinunNajib08  Hi, thanks for trying out 
I suppose most likely it was caused by the pixel detection problem due to different resolution
I usually use 1280x720 and it should work fine

this project is mainly for self-educational purposes only so I haven't put much effort into it
if you want to make it fit your use then I guess you can tweak it a bit the parameters of the coordinates in [this file](https://github.com/nafalabi/albn-fishing-bot/blob/main/src/dimensions.js)
the `pullPoint` and `restPoint` are the ones that you have to pay attention to

**Comment by SoxnGER** [comment]
how run this i got many errors with node module i try install it but same error
